FROM nvcr.io/nvidia/pytorch:23.05-py3
RUN mkdir -p /opt/program
RUN chmod 777 /opt/program
#FROM public.ecr.aws/o7x6j3x6/sd-dreambooth-finetuning-v2


RUN pip install --no-cache-dir fastapi uvicorn sagemaker
RUN pip install sagemaker-ssh-helper
RUN curl -L https://github.com/peak/s5cmd/releases/download/v2.2.2/s5cmd_2.2.2_Linux-64bit.tar.gz | tar -xz && mv s5cmd /opt/program/

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/program:${PATH}"

####install ComfyUI
COPY ComfyUI /opt/program
RUN pip install -r /opt/program/requirements.txt

####upgrade torch/torchversion/cuda121 relevant dependence
#RUN pip install torch torchvision --upgrade --index-url https://download.pytorch.org/whl/cu121
RUN pip install -U xformers
RUN pip install scikit-image
RUN pip install imageio_ffmpeg
RUN pip install wget
RUN pip install retry
RUN pip install blend_modes
RUN pip install transparent_background
#RUN apt install net-tools

###download relevant models
RUN wget https://huggingface.co/mmmoof1/vae-ft-mse-840000-ema-pruned/resolve/main/vae-ft-mse-840000-ema-pruned.safetensors
RUN mv ./vae*.safetensors /opt/program/models/vae/



###install relevant ComfyUI nodes
RUN git clone https://github.com/ltdrdata/ComfyUI-Manager.git /opt/program/custom_nodes/ComfyUI-Manager
RUN git clone https://github.com/qingyuan18/comfyui-llm-node-for-amazon-bedrock.git  /opt/program/custom_nodes/comfyui-llm-node-for-amazon-bedrock
RUN git clone https://github.com/qingyuan18/ComfyUI_LayerStyle.git  /opt/program/custom_nodes/ComfyUI_LayerStyle
RUN git clone https://github.com/Acly/comfyui-tooling-nodes.git    /opt/program/custom_nodes/comfyui-tooling-nodes


RUN git clone https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet.git /opt/program/custom_nodes/ComfyUI-Advanced-ControlNet
RUN git clone https://github.com/Fannovel16/comfyui_controlnet_aux.git /opt/program/custom_nodes/comfyui_controlnet_aux


####install relevant http/socket client（for unicorn web server）
RUN pip3 install websocket-client
RUN pip3 install pydantic
RUN pip install loguru
RUN pip install typer_config
RUN pip install --no-deps diffusers
RUN pip install omegaconf

####install layer style needs module 
RUN pip install --no-cache-dir --force-reinstall  pillow
RUN apt-get update && apt-get install -y libgl1-mesa-glx
RUN pip install opencv-fixer==0.2.5
RUN python -c "from opencv_fixer import AutoFix; AutoFix()"
RUN pip install --no-deps protobuf==3.20.3
RUN pip install --no-deps mediapipe
RUN pip install --no-deps segment_anything

####install paddle ocr relavant module
RUN pip install paddlepaddle-gpu==2.5.1 -i https://mirror.baidu.com/pypi/simple
RUN git clone https://github.com/PaddlePaddle/PaddleOCR
RUN cd PaddleOCR && pip install -r requirements.txt && pip install paddleocr
RUN mkdir -p /home/ubuntu/ComfyUI/models/checkpoints/PaddleOCR/rec && cd /home/ubuntu/ComfyUI/models/checkpoints/PaddleOCR/rec \
     && wget https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_server_infer.tar  \
     && tar -xvf  *.tar

RUN mkdir -p /home/ubuntu/ComfyUI/models/checkpoints/PaddleOCR/det  && cd /home/ubuntu/ComfyUI/models/checkpoints/PaddleOCR/det \
     && wget https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_server_infer.tar  \
     && tar -xvf  *.tar


#####start comfyui
RUN chmod 755 /opt/program
RUN chmod 755 /opt/program/serve
WORKDIR /opt/program

