FROM nvcr.io/nvidia/pytorch:23.05-py3
RUN mkdir -p /opt/program
RUN chmod 777 /opt/program
#FROM public.ecr.aws/o7x6j3x6/sd-dreambooth-finetuning-v2


RUN pip install --no-cache-dir fastapi uvicorn sagemaker
RUN pip install sagemaker-ssh-helper
RUN curl -L https://github.com/peak/s5cmd/releases/download/v2.2.2/s5cmd_2.2.2_Linux-64bit.tar.gz | tar -xz && mv s5cmd /opt/program/

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/program:${PATH}"

####install ComfyUI
COPY ComfyUI /opt/program
RUN pip install -r /opt/program/requirements.txt

####upgrade torch/torchversion/cuda121 relevant dependence
#RUN pip install torch torchvision --upgrade --index-url https://download.pytorch.org/whl/cu121
#RUN pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu124
RUN pip install -U xformers
RUN pip install scikit-image
RUN pip install imageio_ffmpeg
RUN pip install wget
RUN pip install retry
RUN pip install segment-anything

#RUN apt install net-tools

###download relevant models
RUN wget https://huggingface.co/mmmoof1/vae-ft-mse-840000-ema-pruned/resolve/main/vae-ft-mse-840000-ema-pruned.safetensors
RUN wget https://huggingface.co/black-forest-labs/FLUX.1-schnell/resolve/main/ae.safetensors
RUN mv ./vae*.safetensors /opt/program/models/vae/
RUN mv ./ae.safetensors /opt/program/models/vae/



###install relevant ComfyUI nodes
RUN git clone https://github.com/Acly/comfyui-tooling-nodes.git    /opt/program/custom_nodes/comfyui-tooling-nodes
RUN git clone https://github.com/storyicon/comfyui_segment_anything.git /opt/program/custom_nodes/comfyui_segment_anything
RUN git clone https://github.com/pythongosssss/ComfyUI-Custom-Scripts /opt/program/custom_nodes/ComfyUI-Custom-Scripts
RUN git clone https://github.com/ltdrdata/ComfyUI-Manager.git /opt/program/custom_nodes/ComfyUI-Manager
RUN git clone https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet.git /opt/program/custom_nodes/ComfyUI-Advanced-ControlNet
RUN git clone https://github.com/Fannovel16/comfyui_controlnet_aux.git /opt/program/custom_nodes/comfyui_controlnet_aux
RUN git clone https://github.com/XLabs-AI/x-flux-comfyui /opt/program/custom_nodes/x-flux-comfyui
RUN mkdir -p /opt/program/models/xlabs/ipadapters
RUN mkdir -p /opt/program/models/xlabs/loras



####install relevant http/socket client（for unicorn web server）
RUN pip3 install websocket-client
RUN pip3 install pydantic


#####start comfyui
RUN chmod 755 /opt/program
RUN chmod 755 /opt/program/serve
WORKDIR /opt/program

