FROM nvcr.io/nvidia/pytorch:23.05-py3
RUN mkdir -p /opt/program
RUN chmod 777 /opt/program
#FROM public.ecr.aws/o7x6j3x6/sd-dreambooth-finetuning-v2


RUN pip install --no-cache-dir fastapi uvicorn sagemaker
RUN pip install sagemaker-ssh-helper
RUN curl -L https://github.com/peak/s5cmd/releases/download/v2.2.2/s5cmd_2.2.2_Linux-64bit.tar.gz | tar -xz && mv s5cmd /opt/program/

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/program:${PATH}"

####install ComfyUI
COPY ComfyUI /opt/program
RUN pip install -r /opt/program/requirements.txt

####upgrade torch/torchversion/cuda121 relevant dependence
#RUN pip install torch torchvision --upgrade --index-url https://download.pytorch.org/whl/cu121
RUN pip install -U xformers==0.0.27 --no-deps
RUN pip install scikit-image
RUN pip install imageio_ffmpeg
RUN pip install wget
RUN pip install retry
RUN pip install blend_modes
RUN pip install transparent_background
#RUN apt install net-tools

###download relevant models
RUN wget https://huggingface.co/mmmoof1/vae-ft-mse-840000-ema-pruned/resolve/main/vae-ft-mse-840000-ema-pruned.safetensors
RUN mv ./vae*.safetensors /opt/program/models/vae/



###install relevant ComfyUI nodes
RUN git clone https://github.com/ltdrdata/ComfyUI-Manager.git /opt/program/custom_nodes/ComfyUI-Manager
RUN git clone https://github.com/qingyuan18/comfyui-llm-node-for-amazon-bedrock.git  /opt/program/custom_nodes/comfyui-llm-node-for-amazon-bedrock
RUN git clone -b latest https://github.com/qingyuan18/ComfyUI_LayerStyle.git  /opt/program/custom_nodes/ComfyUI_LayerStyle
RUN git clone https://github.com/chflame163/ComfyUI_LayerStyle_Advance.git /opt/program/custom_nodes/ComfyUI_LayerStyle_Advance
RUN git clone https://github.com/Acly/comfyui-tooling-nodes.git    /opt/program/custom_nodes/comfyui-tooling-nodes



####install relevant http/socket client（for unicorn web server）
RUN pip3 install websocket-client
RUN pip3 install pydantic
RUN pip install loguru
RUN pip install typer_config
RUN pip install --no-deps diffusers
RUN pip install omegaconf

####install layer style needs module 
RUN mkdir -p /opt/program/web/extensions/dzNodes
RUN pip install --no-cache-dir --force-reinstall  pillow
RUN apt-get update && apt-get install -y libgl1-mesa-glx
RUN pip install opencv-fixer==0.2.5
RUN python -c "from opencv_fixer import AutoFix; AutoFix()"
RUN pip install --no-deps protobuf==3.20.3
RUN pip install --no-deps mediapipe
RUN pip install --no-deps segment_anything
RUN pip install addict
RUN pip install yapf



####install paddle ocr relavant module
RUN pip install paddlepaddle-gpu==2.6.2
RUN pip install paddleocr==2.10.0

#####start comfyui
RUN chmod 755 /opt/program
RUN chmod 755 /opt/program/serve
WORKDIR /opt/program

